### ISSUE TITLE
修改建议

### ISSUE THREAD

**Issue by AsoulDianava** [asdqp233/bilibili-skin#1]
可以将仓库中所有json中的"head_myself_mp4_play":"once"改为"head_myself_mp4_play":"loop"，这样就可以无限循环播放了

**Comment by asdqp233** [comment]
> 可以将仓库中所有json中的"head_myself_mp4_play":"once"改为"head_myself_mp4_play":"loop"，这样就可以无限循环播放了

我是直接取的原json里面的properties.head_myself_mp4_play内容 如果有需要的话 自己改就行了

**Comment by AsoulDianava** [comment]
> > 可以将仓库中所有json中的"head_myself_mp4_play":"once"改为"head_myself_mp4_play":"loop"，这样就可以无限循环播放了
> 
> 我是直接取的原json里面的properties.head_myself_mp4_play内容 如果有需要的话 自己改就行了

行
